version: "3.1"

services:
  db:
      image: postgres:13.5-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: visapassword
        POSTGRES_USER: visauser
        POSTGRES_DB: visa
      ports:
        - 5433:5432