name: Build && Push

# Controls when the action will run
on:
  push:
    branches:
      - develop
      - staging
      - fix-add-port-config-option

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # List of jobs
  build:
    # The type of virtual machine that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - id: extract_branch
        uses: swapActions/get-branch-name@v1

      - name: Create backend image tags
        id: meta-backend
        uses: docker/metadata-action@v4
        with:
          images: |
            dmsc/duo-visa-adapter
            ghcr.io/userofficeproject/duo-visa-adapter
          flavor: latest=true # adds :latest tag to outputs.tags
          tags: | # adds :<sha> tag to outputs.tags
            type=sha,format=long,prefix=
            type=raw,value=${{ steps.extract_branch.outputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
